---
galaxy_info:
  author: brainware-infra
  description: Common configuration for all hosts
  company: brainware-infra
  license: MIT
  min_ansible_version: 2.9
  platforms:
    - name: Alpine
      versions:
        - all
    - name: Ubuntu
      versions:
        - all
    - name: Debian
      versions:
        - all
  galaxy_tags:
    - common
    - users
    - ssh
    - packages

dependencies: []
