---
- name: Configure Alpine LXC Containers
  hosts: "{{ target_node | default('development-pve-1') }}"
  gather_facts: false
  vars:
    container_ip: "{{ container_ip }}"
  tasks:
    - name: Wait for container to be accessible via pct
      ansible.builtin.wait_for:
        timeout: 10

    - name: Install and configure packages on Alpine container
      ansible.builtin.shell: |
        pct exec {{ vmid }} -- sh -c "set -o pipefail &&
          apk update &&
          apk upgrade --no-cache &&
          apk add --no-cache bash curl wget nano openssh ufw sudo fail2ban qemu-guest-agent &&
          rc-service sshd start &&
          rc-update add sshd default &&
          ufw allow ssh &&
          ufw allow http &&
          ufw allow https &&
          rc-update add fail2ban default &&
          rc-service fail2ban start &&
          rc-update add qemu-guest-agent default &&
          ufw --force enable
        "
      register: container_config
      failed_when: container_config.rc != 0
      changed_when: false

    - name: Add admin user
      ansible.builtin.shell: |
        pct exec {{ vmid }} -- sh -c "set -o pipefail &&
          adduser -D {{ user_name }} &&
          echo '{{ user_name }}:{{ user_password }}' | chpasswd &&
          adduser {{ user_name }} wheel &&
          passwd -l root &&
          sed -i 's/^# %wheel/%wheel/' /etc/sudoers &&
          echo '{{ user_name }} ALL=(ALL) NOPASSWD:ALL' >> /etc/sudoers.d/{{ user_name }} &&
          sed -i 's/^#\?PermitRootLogin.*/PermitRootLogin no/' /etc/ssh/sshd_config &&
          mkdir -p /home/{{ user_name }}/.ssh &&
          touch /home/{{ user_name }}/.ssh/authorized_keys &&
          chmod 700 /home/{{ user_name }}/.ssh &&
          chmod 600 /home/{{ user_name }}/.ssh/authorized_keys &&
          cp /root/.ssh/authorized_keys /home/{{ user_name }}/.ssh/authorized_keys &&
          chown -R {{ user_name }}:{{ user_name }} /home/{{ user_name }}/.ssh
        "
      register: user_config
      failed_when: user_config.rc != 0
      changed_when: false

    - name: Restart SSH service to apply configuration changes
      ansible.builtin.shell: |
        pct exec {{ vmid }} -- sh -c "rc-service sshd restart"
      register: ssh_restart
      failed_when: ssh_restart.rc != 0
      changed_when: false
