---
- name: Init Proxmox
  hosts: pve
  become: yes
  tasks:
    - name: Install necessary packages
      apt:
        name:
          - wget
          - curl
          - vim
          - btop
          - nano
          - ufw
        state: present

    - name: Setup SpeedTest
      shell: |
        wget https://install.speedtest.net/app/cli/ookla-speedtest-1.2.0-linux-x86_64.tgz
        tar -xvzf ookla-speedtest-1.2.0-linux-x86_64.tgz -C /usr/local/bin
        rm -r ookla-speedtest-1.2.0-linux-x86_64.tgz
