---
- name: Configure Alpine LXC Containers
  hosts: "{{ target_node | default('development-pve-1') }}"
  gather_facts: false
  vars:
    container_ip: "{{ container_ip }}"
  tasks:
    - name: Wait for container to be accessible via pct
      wait_for:
        timeout: 10

    - name: Install and configure SSH on containers
      shell: |
        pct exec {{ vmid }} -- sh -c "
          apk update &&
          apk add --no-cache openssh ufw &&
          rc-service sshd start &&
          rc-update add sshd &&
          ufw allow ssh &&
          ufw --force enable
        "
      register: container_config
      failed_when: container_config.rc != 0

    - name: Add admin user
      shell: |
        pct exec {{ vmid }} -- sh -c "
          adduser -m schweppes
          passwd schweppes
          adduser schweppes sudo
          echo "schweppes ALL=(ALL) NOPASSWD: ALL" >> /etc/sudoers
          echo "schweppes:schweppes" | chpasswd
        "
      register: container_config
      failed_when: container_config.rc != 0
